//
// Created by mikhail on 03.02.19.
//

#ifndef NETWORKSLAB2019HSE_CURRENCYCLIENTAPPLICATION_H
#define NETWORKSLAB2019HSE_CURRENCYCLIENTAPPLICATION_H


class CurrencyClientApplication {

};


#endif //NETWORKSLAB2019HSE_CURRENCYCLIENTAPPLICATION_H
